### ISSUE TITLE
Is there a forum or other discussion area?

### ISSUE THREAD

**Issue by abrugsch** [gazzmaniac/Amiga-SMD-500#1]
I found someone selling a copy of this this board on ebay and it's something that I wanted to do myself (glad to see you're using KiCad... I can contribute pull requests ;) ). The A500++ is all well and good but it uses the exact same through hole parts as the original. I'd like to see how people building this are getting on as I love that it has a load of the modern mods built right in.

Is there a dev thread on EAB? or a discord server such as Official Commodore Amiga, Retro Man Cave, Amiga Bill's?

**Comment by gazzmaniac** [comment]
I haven't got any formal discussion etc. but I am making one and posting progress on Facebook at facebook.com/redkegtech.
I have no idea if anyone has got one running yet.  I've got an issue getting sync from Agnus but I'm away for work for a couple of weeks so progress has stalled.
